export const warningHeader = `/**
 * This file is generated by @qinzisong/types-generator and should not be edited.
 * It will be overwritten the next time types are generated.
 * https://github.com/qinzisong/types-generator
 */

`;
